import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
import { Cinzel, Italianno, Marcellus } from '@next/font/google';


const cinzel = Cinzel({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  display: 'swap',
  variable: '--font-cinzel', // optional CSS variable
});

const italianno = Italianno({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-italianno',
});

const marcellus = Marcellus({
  subsets: ['latin'],
  weight: ['400'],
  display: 'swap',
  variable: '--font-marcellus',
});



export const metadata = {
  title: "Varsity Math",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable} ${cinzel.variable} ${italianno.variable} ${marcellus.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}

